# Generated by Django 5.1.4 on 2025-04-10 04:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('service', 'Service'), ('food', 'Food & Beverage'), ('other', 'Other')], max_length=20)),
                ('year_started', models.IntegerField()),
                ('employee_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('annual_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('has_financial_records', models.BooleanField(default=False)),
                ('has_invoice_system', models.BooleanField(default=False)),
                ('has_website', models.BooleanField(default=False)),
                ('has_online_store', models.BooleanField(default=False)),
                ('has_social_media', models.BooleanField(default=False)),
                ('has_npwp', models.BooleanField(default=False)),
                ('has_profit_loss_statement', models.BooleanField(default=False)),
                ('has_balance_sheet', models.BooleanField(default=False)),
                ('business_goals', models.TextField()),
                ('interested_in_mentoring', models.BooleanField(default=False)),
                ('digital_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('financial_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('legal_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('operational_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('business_level', models.CharField(blank=True, choices=[('micro', 'Micro'), ('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('report_ready', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadinessAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('partial', 'Partial')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='readiness.readinessassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='readiness.readinessquestion')),
            ],
            options={
                'ordering': ['question__category', 'question__id'],
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
